---
hide_body: true
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: textarea
  name: description
  label: Description
  description: A short description of the page
  config:
    required: true
- type: datetime
  name: publish_date
  label: Publish Date
  config:
    required: true
- type: text
  name: layout
  label: layout
  hidden: true
  default: post
- type: text
- type: image_gallery
  default:
  - "/uploads/2018/02/17/bridge.jpg"
  - "/uploads/2017/11/14/jeffrey-wegrzyn-183858.jpg"
  - "/uploads/2017/11/14/joseph-gonzalez-399972.jpg"
  - "/uploads/2018/02/25/car.jpg"
  - "/uploads/2017/11/13/dal-logo.png"
  - "/uploads/2018/02/17/building2.jpg"
  name: '1'
  label: '1'
  description: '1'
