---
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  default: '0'
- name: sub_heading
  label: Sub Heading
  type: text
  hidden: false
  default: ''
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- type: image_gallery
  name: '00'
  label: '0'
  description: '0'
  default:
  - "/uploads/2018/02/17/neurons.jpg"
  - "/uploads/2017/11/14/filipe-almeida-192048 (1).jpg"
  - "/uploads/2017/11/13/stem.png"
  - "/uploads/2018/02/17/bridge3.jpg"
  - "/uploads/2017/11/13/nysed.png"
  - "/uploads/2017/11/13/health.png"
  - "/uploads/2018/02/17/city.jpg"
